# Limit lines to 90 characters.
LineLength:
  Max: 90

ClassLength:
  Enabled: false

# Avoid single-line methods.
SingleLineMethods:
  AllowIfMethodIsEmpty: true

StringLiterals:
  Enabled: false

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Use trailing rather than leading dots on multi-line call chains
Style/DotPosition:
  EnforcedStyle: trailing

# Whatever
Style/Documentation:
  Enabled: false

# RSpec argument matchers use ===. Sorry cop.
Style/CaseEquality:
  Enabled: false
